Casino/src/objects/Player__c.object
<CustomObject>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Casino/src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Deposit</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Withdrawal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <recordTypes>
        <fullName>Deposit</fullName>
        <active>true</active>
        <label>Deposit</label>
    </recordTypes>
    <recordTypes>
        <fullName>Withdrawal</fullName>
        <active>true</active>
        <label>Withdrawal</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Casino/src/classes/transTestTrigger.cls
@isTest
public class transTestTrigger {
    @isTest
    public static void testTransInsert(){//checks for failure because withdrawal of 1000 from balance of 0
        Player__c playid = new Player__c(Name='testUser1');
        insert playid;
        playid=[SELECT Id,Balance__C From Player__c WHERE Id=:playid.Id];
        System.debug(playid.Balance__c);
        Transaction__c test;
        Transaction__c test2;
        Id recTypeId = Schema.SObjectType.Transaction__c.getRecordTypeInfosByName().get('Withdrawal').getRecordTypeId();
        Id recTypeId2 = Schema.SObjectType.Transaction__c.getRecordTypeInfosByName().get('Deposit').getRecordTypeId();
        try{
            test2 = new Transaction__c(player__c=playid.Id,Amount__c=1,RecordTypeId=recTypeId2,Transaction_Type__c='Deposit');
            insert test2;
            System.debug([SELECT id,amount__c FROM Transaction__c WHERE id=:test2.Id]);
            test = new Transaction__c(player__c=playid.Id,Amount__c=1000,RecordTypeId=recTypeId,Transaction_Type__c='Withdrawal');
            insert test;
            System.debug([SELECT id,amount__c,Transaction_Type__c FROM Transaction__c WHERE id=:test.Id]);
        }catch(Exception e){
            System.debug('failed the insert');
            System.assert(True);
        }
    }
    @isTest
    public static void testTransFail(){//checks for success because withdraw 0
        Player__c playid = new Player__c(Name='testUser1');
        insert playid;
        Transaction__c test;
        Id recTypeId = Schema.SObjectType.Transaction__c.getRecordTypeInfosByName().get('Withdrawal').getRecordTypeId();
        try{
            test = new Transaction__c(player__c=playid.Id,Amount__c=0,RecordTypeId=recTypeId,Transaction_Type__c='Withdrawal');
            insert test;
            System.assert(true);
        }catch(Exception e){
            System.assert(false);
        }
    }
}