Casino/src/objects/Player__c.object
<CustomObject>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Casino/src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Casino/src/classes/TransactionCreateController.cls
public class TransactionCreateController {
    
    public Transaction__c userTransaction{
        get{
            if(userTransaction == null){
                userTransaction = new Transaction__c();
                SObject playerId = [SELECT Id FROM Player__c WHERE OwnerId = :UserInfo.getUserId() LIMIT 1]; 
                userTransaction.Player__c = playerId.Id;
            }
            return userTransaction;
        }
        set;
    }
    
    public PageReference save(){
        try{
            Database.SaveResult transactionInsertResult = Database.insert(userTransaction);
       	}catch(DMLException e){
        	System.debug('You caused a DML error' + e.getMessage());      
        }
        return null;
        
    }

}